// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA77_g_lwdXf_Om_Ncc73f900OCI0Yo2wE',
    appId: '1:104091613425:web:eb7170b694f71b01ebd150',
    messagingSenderId: '104091613425',
    projectId: 'facebook-clone-97bcf',
    authDomain: 'facebook-clone-97bcf.firebaseapp.com',
    storageBucket: 'facebook-clone-97bcf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjVkZT_t31BV69CjCBe-RBqzNQ4KhoP4A',
    appId: '1:104091613425:android:9c8be9cdf1fe8658ebd150',
    messagingSenderId: '104091613425',
    projectId: 'facebook-clone-97bcf',
    storageBucket: 'facebook-clone-97bcf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEkS8DT6x2Kae1fQqZ9gj8sB7q6eZDgD4',
    appId: '1:104091613425:ios:1c7b3b4efdd25d48ebd150',
    messagingSenderId: '104091613425',
    projectId: 'facebook-clone-97bcf',
    storageBucket: 'facebook-clone-97bcf.appspot.com',
    iosBundleId: 'com.example.facebookClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEkS8DT6x2Kae1fQqZ9gj8sB7q6eZDgD4',
    appId: '1:104091613425:ios:be0216decea6ae7febd150',
    messagingSenderId: '104091613425',
    projectId: 'facebook-clone-97bcf',
    storageBucket: 'facebook-clone-97bcf.appspot.com',
    iosBundleId: 'com.example.facebookClone.RunnerTests',
  );
}
